# Funding configuration for NexusAuth
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: # [SebastiaWeb]

# Open Collective
# open_collective: nexus-auth

# Ko-fi
# ko_fi: SebastiaWeb

# Patreon
# patreon: SebastiaWeb

# Buy Me a Coffee
# custom: ['https://www.buymeacoffee.com/SebastiaWeb']
