labels: [discussion, showcase]

body:
  - type: markdown
    attributes:
      value: |
        ## 🎨 Show and Tell

        Built something cool with NexusAuth? Share it with the community!

  - type: textarea
    id: project
    attributes:
      label: What did you build?
      description: Tell us about your project
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Project Link
      description: Share a link (optional)
      placeholder: https://...
    validations:
      required: false

  - type: textarea
    id: experience
    attributes:
      label: Your Experience
      description: How was your experience using NexusAuth?
    validations:
      required: false
