name: 🐛 Bug Report
description: Report a bug or unexpected behavior in NexusAuth
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install '@nexus-auth/core'
        2. Configure with '...'
        3. Call method '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Actual behavior...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Minimal code example to reproduce the issue
      render: typescript
      placeholder: |
        import { NexusAuth } from '@nexus-auth/core';

        const auth = new NexusAuth({
          // your config
        });

        // code that triggers the bug
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Affected Package(s)
      description: Which package(s) are affected?
      multiple: true
      options:
        - "@nexus-auth/core"
        - "@nexus-auth/typeorm-adapter"
        - "@nexus-auth/prisma-adapter"
        - "@nexus-auth/mongoose-adapter"
        - "@nexus-auth/sql-adapter"
        - "@nexus-auth/providers"
        - "@nexus-auth/nextjs-helpers"
        - "@nexus-auth/nestjs-helpers"
        - "@nexus-auth/express-helpers"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: What framework are you using?
      options:
        - "Next.js"
        - "NestJS"
        - "Express"
        - "Other (please specify in description)"
        - "None / Standalone"
    validations:
      required: true

  - type: dropdown
    id: database
    attributes:
      label: Database
      description: What database are you using?
      options:
        - "PostgreSQL"
        - "MySQL"
        - "SQLite"
        - "MongoDB"
        - "MSSQL"
        - "Other (please specify in description)"
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "20.10.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Additional environment details
      placeholder: |
        - OS: macOS 14.0
        - Package Manager: pnpm 8.0.0
        - TypeScript: 5.3.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Stack Trace
      description: If applicable, add error logs or stack trace
      render: shell
      placeholder: Paste error logs here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all requested information
          required: true
        - label: I am using the latest version of the package
          required: false
