name: 📚 Documentation Issue
description: Report an issue with documentation or suggest documentation improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      description: What type of documentation issue is this?
      options:
        - "Missing documentation"
        - "Incorrect/outdated documentation"
        - "Unclear/confusing documentation"
        - "Typo or grammar error"
        - "Broken links"
        - "Missing examples"
        - "API reference issue"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue? (URL or file path)
      placeholder: "https://github.com/SebastiaWeb/nexus-auth/blob/main/README.md or packages/core/README.md"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the documentation issue
      placeholder: What's wrong or missing?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: Provide your suggested changes or additions...
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Affected Package(s)
      description: Which package documentation is affected?
      multiple: true
      options:
        - "@nexusauth/core"
        - "@nexusauth/typeorm-adapter"
        - "@nexusauth/prisma-adapter"
        - "@nexusauth/mongoose-adapter"
        - "@nexusauth/sql-adapter"
        - "@nexusauth/providers"
        - "@nexusauth/nextjs-helpers"
        - "@nexusauth/nestjs-helpers"
        - "@nexusauth/express-helpers"
        - "General documentation"
        - "Guides"
    validations:
      required: true

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you be willing to help?
      options:
        - label: I would be willing to submit a PR to fix this

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
