name: ✨ Feature Request
description: Suggest a new feature or enhancement for NexusAuth
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your input.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: Alternative approaches...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you would use this feature
      render: typescript
      placeholder: |
        // Example of how the feature would work
        const auth = new NexusAuth({
          newFeature: {
            // configuration
          }
        });
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Affected Package(s)
      description: Which package(s) would this feature affect?
      multiple: true
      options:
        - "@nexus-auth/core"
        - "@nexus-auth/typeorm-adapter"
        - "@nexus-auth/prisma-adapter"
        - "@nexus-auth/mongoose-adapter"
        - "@nexus-auth/sql-adapter"
        - "@nexus-auth/providers"
        - "@nexus-auth/nextjs-helpers"
        - "@nexus-auth/nestjs-helpers"
        - "@nexus-auth/express-helpers"
        - "New package"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my work"
        - "High - Would significantly improve my workflow"
        - "Medium - Nice to have"
        - "Low - Minor improvement"
    validations:
      required: true

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to write documentation for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: Additional information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature doesn't already exist in the library
          required: true
