name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto assign PR to author
        uses: toshimaru/auto-author-assign@v2.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
